# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/graph_settings_dialog.ui'
#
# Created: Thu Nov  8 19:39:42 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(531, 317)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.titleFontCombo = QtGui.QFontComboBox(self.groupBox)
        self.titleFontCombo.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.titleFontCombo.setObjectName(_fromUtf8("titleFontCombo"))
        self.gridLayout.addWidget(self.titleFontCombo, 0, 1, 1, 1)
        self.titleSizeSpin = QtGui.QSpinBox(self.groupBox)
        self.titleSizeSpin.setMinimum(1)
        self.titleSizeSpin.setProperty(_fromUtf8("value"), 16)
        self.titleSizeSpin.setObjectName(_fromUtf8("titleSizeSpin"))
        self.gridLayout.addWidget(self.titleSizeSpin, 0, 2, 1, 1)
        self.titleBoldBtn = QtGui.QToolButton(self.groupBox)
        self.titleBoldBtn.setStyleSheet(_fromUtf8("font-weight: bold"))
        self.titleBoldBtn.setCheckable(True)
        self.titleBoldBtn.setObjectName(_fromUtf8("titleBoldBtn"))
        self.gridLayout.addWidget(self.titleBoldBtn, 0, 4, 1, 1)
        self.titleItalicBtn = QtGui.QToolButton(self.groupBox)
        self.titleItalicBtn.setStyleSheet(_fromUtf8("font-style: italic"))
        self.titleItalicBtn.setCheckable(True)
        self.titleItalicBtn.setObjectName(_fromUtf8("titleItalicBtn"))
        self.gridLayout.addWidget(self.titleItalicBtn, 0, 5, 1, 1)
        self.titleColorBtn = QtGui.QToolButton(self.groupBox)
        self.titleColorBtn.setObjectName(_fromUtf8("titleColorBtn"))
        self.gridLayout.addWidget(self.titleColorBtn, 0, 7, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setIndent(20)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 6, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelsSizeSpin = QtGui.QSpinBox(self.groupBox_2)
        self.labelsSizeSpin.setMinimum(1)
        self.labelsSizeSpin.setProperty(_fromUtf8("value"), 14)
        self.labelsSizeSpin.setObjectName(_fromUtf8("labelsSizeSpin"))
        self.gridLayout_2.addWidget(self.labelsSizeSpin, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.labelsFontCombo = QtGui.QFontComboBox(self.groupBox_2)
        self.labelsFontCombo.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.labelsFontCombo.setObjectName(_fromUtf8("labelsFontCombo"))
        self.gridLayout_2.addWidget(self.labelsFontCombo, 0, 1, 1, 1)
        self.labelsBoldBtn = QtGui.QToolButton(self.groupBox_2)
        self.labelsBoldBtn.setStyleSheet(_fromUtf8("font-weight: bold"))
        self.labelsBoldBtn.setCheckable(True)
        self.labelsBoldBtn.setObjectName(_fromUtf8("labelsBoldBtn"))
        self.gridLayout_2.addWidget(self.labelsBoldBtn, 0, 4, 1, 1)
        self.labelsItalicBtn = QtGui.QToolButton(self.groupBox_2)
        self.labelsItalicBtn.setStyleSheet(_fromUtf8("font-style: italic"))
        self.labelsItalicBtn.setCheckable(True)
        self.labelsItalicBtn.setObjectName(_fromUtf8("labelsItalicBtn"))
        self.gridLayout_2.addWidget(self.labelsItalicBtn, 0, 5, 1, 1)
        self.labelsColorBtn = QtGui.QToolButton(self.groupBox_2)
        self.labelsColorBtn.setObjectName(_fromUtf8("labelsColorBtn"))
        self.gridLayout_2.addWidget(self.labelsColorBtn, 0, 7, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setIndent(20)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 6, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.pointsColorBtn = QtGui.QToolButton(self.groupBox_3)
        self.pointsColorBtn.setObjectName(_fromUtf8("pointsColorBtn"))
        self.horizontalLayout_2.addWidget(self.pointsColorBtn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.pointsReplicasColorBtn = QtGui.QToolButton(self.groupBox_3)
        self.pointsReplicasColorBtn.setObjectName(_fromUtf8("pointsReplicasColorBtn"))
        self.horizontalLayout_2.addWidget(self.pointsReplicasColorBtn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.linesColorBtn = QtGui.QToolButton(self.groupBox_4)
        self.linesColorBtn.setObjectName(_fromUtf8("linesColorBtn"))
        self.horizontalLayout.addWidget(self.linesColorBtn)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.linesThrendColorBtn = QtGui.QToolButton(self.groupBox_4)
        self.linesThrendColorBtn.setObjectName(_fromUtf8("linesThrendColorBtn"))
        self.horizontalLayout.addWidget(self.linesThrendColorBtn)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Impostazioni", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Font", None, QtGui.QApplication.UnicodeUTF8))
        self.titleBoldBtn.setText(QtGui.QApplication.translate("Dialog", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.titleItalicBtn.setText(QtGui.QApplication.translate("Dialog", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.titleColorBtn.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Labels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Font", None, QtGui.QApplication.UnicodeUTF8))
        self.labelsBoldBtn.setText(QtGui.QApplication.translate("Dialog", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.labelsItalicBtn.setText(QtGui.QApplication.translate("Dialog", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.labelsColorBtn.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Points", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Default color", None, QtGui.QApplication.UnicodeUTF8))
        self.pointsColorBtn.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Replicas\' color", None, QtGui.QApplication.UnicodeUTF8))
        self.pointsReplicasColorBtn.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "Lines color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Default color", None, QtGui.QApplication.UnicodeUTF8))
        self.linesColorBtn.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Thrend lines\' color", None, QtGui.QApplication.UnicodeUTF8))
        self.linesThrendColorBtn.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))

