# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/graph_settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(531, 317)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.titleFontCombo = QtWidgets.QFontComboBox(self.groupBox)
        self.titleFontCombo.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.titleFontCombo.setObjectName("titleFontCombo")
        self.gridLayout.addWidget(self.titleFontCombo, 0, 1, 1, 1)
        self.titleSizeSpin = QtWidgets.QSpinBox(self.groupBox)
        self.titleSizeSpin.setMinimum(1)
        self.titleSizeSpin.setProperty("value", 16)
        self.titleSizeSpin.setObjectName("titleSizeSpin")
        self.gridLayout.addWidget(self.titleSizeSpin, 0, 2, 1, 1)
        self.titleBoldBtn = QtWidgets.QToolButton(self.groupBox)
        self.titleBoldBtn.setStyleSheet("font-weight: bold")
        self.titleBoldBtn.setCheckable(True)
        self.titleBoldBtn.setObjectName("titleBoldBtn")
        self.gridLayout.addWidget(self.titleBoldBtn, 0, 4, 1, 1)
        self.titleItalicBtn = QtWidgets.QToolButton(self.groupBox)
        self.titleItalicBtn.setStyleSheet("font-style: italic")
        self.titleItalicBtn.setCheckable(True)
        self.titleItalicBtn.setObjectName("titleItalicBtn")
        self.gridLayout.addWidget(self.titleItalicBtn, 0, 5, 1, 1)
        self.titleColorBtn = QtWidgets.QToolButton(self.groupBox)
        self.titleColorBtn.setObjectName("titleColorBtn")
        self.gridLayout.addWidget(self.titleColorBtn, 0, 7, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setIndent(20)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 6, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelsSizeSpin = QtWidgets.QSpinBox(self.groupBox_2)
        self.labelsSizeSpin.setMinimum(1)
        self.labelsSizeSpin.setProperty("value", 14)
        self.labelsSizeSpin.setObjectName("labelsSizeSpin")
        self.gridLayout_2.addWidget(self.labelsSizeSpin, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.labelsFontCombo = QtWidgets.QFontComboBox(self.groupBox_2)
        self.labelsFontCombo.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.labelsFontCombo.setObjectName("labelsFontCombo")
        self.gridLayout_2.addWidget(self.labelsFontCombo, 0, 1, 1, 1)
        self.labelsBoldBtn = QtWidgets.QToolButton(self.groupBox_2)
        self.labelsBoldBtn.setStyleSheet("font-weight: bold")
        self.labelsBoldBtn.setCheckable(True)
        self.labelsBoldBtn.setObjectName("labelsBoldBtn")
        self.gridLayout_2.addWidget(self.labelsBoldBtn, 0, 4, 1, 1)
        self.labelsItalicBtn = QtWidgets.QToolButton(self.groupBox_2)
        self.labelsItalicBtn.setStyleSheet("font-style: italic")
        self.labelsItalicBtn.setCheckable(True)
        self.labelsItalicBtn.setObjectName("labelsItalicBtn")
        self.gridLayout_2.addWidget(self.labelsItalicBtn, 0, 5, 1, 1)
        self.labelsColorBtn = QtWidgets.QToolButton(self.groupBox_2)
        self.labelsColorBtn.setObjectName("labelsColorBtn")
        self.gridLayout_2.addWidget(self.labelsColorBtn, 0, 7, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setIndent(20)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 6, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.pointsColorBtn = QtWidgets.QToolButton(self.groupBox_3)
        self.pointsColorBtn.setObjectName("pointsColorBtn")
        self.horizontalLayout_2.addWidget(self.pointsColorBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.pointsReplicasColorBtn = QtWidgets.QToolButton(self.groupBox_3)
        self.pointsReplicasColorBtn.setObjectName("pointsReplicasColorBtn")
        self.horizontalLayout_2.addWidget(self.pointsReplicasColorBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.linesColorBtn = QtWidgets.QToolButton(self.groupBox_4)
        self.linesColorBtn.setObjectName("linesColorBtn")
        self.horizontalLayout.addWidget(self.linesColorBtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.linesThrendColorBtn = QtWidgets.QToolButton(self.groupBox_4)
        self.linesThrendColorBtn.setObjectName("linesThrendColorBtn")
        self.horizontalLayout.addWidget(self.linesThrendColorBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Impostazioni"))
        self.groupBox.setTitle(_translate("Dialog", "Title"))
        self.label.setText(_translate("Dialog", "Font"))
        self.titleBoldBtn.setText(_translate("Dialog", "A"))
        self.titleItalicBtn.setText(_translate("Dialog", "A"))
        self.titleColorBtn.setText(_translate("Dialog", "..."))
        self.label_4.setText(_translate("Dialog", "Color"))
        self.groupBox_2.setTitle(_translate("Dialog", "Labels"))
        self.label_2.setText(_translate("Dialog", "Font"))
        self.labelsBoldBtn.setText(_translate("Dialog", "A"))
        self.labelsItalicBtn.setText(_translate("Dialog", "A"))
        self.labelsColorBtn.setText(_translate("Dialog", "..."))
        self.label_5.setText(_translate("Dialog", "Color"))
        self.groupBox_3.setTitle(_translate("Dialog", "Points"))
        self.label_3.setText(_translate("Dialog", "Default color"))
        self.pointsColorBtn.setText(_translate("Dialog", "..."))
        self.label_7.setText(_translate("Dialog", "Replicas\' color"))
        self.pointsReplicasColorBtn.setText(_translate("Dialog", "..."))
        self.groupBox_4.setTitle(_translate("Dialog", "Lines color"))
        self.label_6.setText(_translate("Dialog", "Default color"))
        self.linesColorBtn.setText(_translate("Dialog", "..."))
        self.label_8.setText(_translate("Dialog", "Thrend lines\' color"))
        self.linesThrendColorBtn.setText(_translate("Dialog", "..."))

