# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/risknat_toolbar.ui'
#
# Created: Wed Aug  1 12:16:41 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_RiskNatToolBar(object):
    def setupUi(self, RiskNatToolBar):
        RiskNatToolBar.setObjectName(_fromUtf8("RiskNatToolBar"))
        RiskNatToolBar.resize(797, 126)
        RiskNatToolBar.setWindowTitle(_fromUtf8(""))
        self.horizontalLayout = QtGui.QHBoxLayout(RiskNatToolBar)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(RiskNatToolBar)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setMargin(4)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.minDateEdit = QtGui.QDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minDateEdit.sizePolicy().hasHeightForWidth())
        self.minDateEdit.setSizePolicy(sizePolicy)
        self.minDateEdit.setObjectName(_fromUtf8("minDateEdit"))
        self.gridLayout.addWidget(self.minDateEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.maxDateEdit = QtGui.QDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxDateEdit.sizePolicy().hasHeightForWidth())
        self.maxDateEdit.setSizePolicy(sizePolicy)
        self.maxDateEdit.setObjectName(_fromUtf8("maxDateEdit"))
        self.gridLayout.addWidget(self.maxDateEdit, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.minYEdit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minYEdit.sizePolicy().hasHeightForWidth())
        self.minYEdit.setSizePolicy(sizePolicy)
        self.minYEdit.setObjectName(_fromUtf8("minYEdit"))
        self.horizontalLayout_2.addWidget(self.minYEdit)
        self.label_4 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setIndent(4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.maxYEdit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxYEdit.sizePolicy().hasHeightForWidth())
        self.maxYEdit.setSizePolicy(sizePolicy)
        self.maxYEdit.setObjectName(_fromUtf8("maxYEdit"))
        self.horizontalLayout_2.addWidget(self.maxYEdit)
        self.refreshScaleButton = QtGui.QToolButton(self.groupBox)
        self.refreshScaleButton.setObjectName(_fromUtf8("refreshScaleButton"))
        self.horizontalLayout_2.addWidget(self.refreshScaleButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 2)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(RiskNatToolBar)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setMargin(4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.replicaUpCheck = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replicaUpCheck.sizePolicy().hasHeightForWidth())
        self.replicaUpCheck.setSizePolicy(sizePolicy)
        self.replicaUpCheck.setObjectName(_fromUtf8("replicaUpCheck"))
        self.verticalLayout.addWidget(self.replicaUpCheck)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.replicaDistEdit = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replicaDistEdit.sizePolicy().hasHeightForWidth())
        self.replicaDistEdit.setSizePolicy(sizePolicy)
        self.replicaDistEdit.setText(_fromUtf8("28"))
        self.replicaDistEdit.setObjectName(_fromUtf8("replicaDistEdit"))
        self.horizontalLayout_3.addWidget(self.replicaDistEdit)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.replicaDownCheck = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replicaDownCheck.sizePolicy().hasHeightForWidth())
        self.replicaDownCheck.setSizePolicy(sizePolicy)
        self.replicaDownCheck.setObjectName(_fromUtf8("replicaDownCheck"))
        self.verticalLayout.addWidget(self.replicaDownCheck)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(RiskNatToolBar)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.hGridCheck = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hGridCheck.sizePolicy().hasHeightForWidth())
        self.hGridCheck.setSizePolicy(sizePolicy)
        self.hGridCheck.setObjectName(_fromUtf8("hGridCheck"))
        self.gridLayout_3.addWidget(self.hGridCheck, 0, 0, 1, 1)
        self.linRegrCheck = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linRegrCheck.sizePolicy().hasHeightForWidth())
        self.linRegrCheck.setSizePolicy(sizePolicy)
        self.linRegrCheck.setObjectName(_fromUtf8("linRegrCheck"))
        self.gridLayout_3.addWidget(self.linRegrCheck, 0, 1, 1, 1)
        self.vGridCheck = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vGridCheck.sizePolicy().hasHeightForWidth())
        self.vGridCheck.setSizePolicy(sizePolicy)
        self.vGridCheck.setObjectName(_fromUtf8("vGridCheck"))
        self.gridLayout_3.addWidget(self.vGridCheck, 1, 0, 1, 1)
        self.smoothCheck = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.smoothCheck.sizePolicy().hasHeightForWidth())
        self.smoothCheck.setSizePolicy(sizePolicy)
        self.smoothCheck.setObjectName(_fromUtf8("smoothCheck"))
        self.gridLayout_3.addWidget(self.smoothCheck, 1, 1, 1, 1)
        self.linesCheck = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linesCheck.sizePolicy().hasHeightForWidth())
        self.linesCheck.setSizePolicy(sizePolicy)
        self.linesCheck.setObjectName(_fromUtf8("linesCheck"))
        self.gridLayout_3.addWidget(self.linesCheck, 2, 0, 1, 1)
        self.labelsCheck = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelsCheck.sizePolicy().hasHeightForWidth())
        self.labelsCheck.setSizePolicy(sizePolicy)
        self.labelsCheck.setObjectName(_fromUtf8("labelsCheck"))
        self.gridLayout_3.addWidget(self.labelsCheck, 3, 0, 1, 1)
        self.legendCheck_2 = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legendCheck_2.sizePolicy().hasHeightForWidth())
        self.legendCheck_2.setSizePolicy(sizePolicy)
        self.legendCheck_2.setObjectName(_fromUtf8("legendCheck_2"))
        self.gridLayout_3.addWidget(self.legendCheck_2, 3, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(RiskNatToolBar)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setMargin(4)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.xLabelEdit = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xLabelEdit.sizePolicy().hasHeightForWidth())
        self.xLabelEdit.setSizePolicy(sizePolicy)
        self.xLabelEdit.setObjectName(_fromUtf8("xLabelEdit"))
        self.gridLayout_4.addWidget(self.xLabelEdit, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setIndent(4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.yLabelEdit = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yLabelEdit.sizePolicy().hasHeightForWidth())
        self.yLabelEdit.setSizePolicy(sizePolicy)
        self.yLabelEdit.setObjectName(_fromUtf8("yLabelEdit"))
        self.gridLayout_4.addWidget(self.yLabelEdit, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(RiskNatToolBar)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setMargin(4)
        self.gridLayout_5.setSpacing(2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.titleParam1Edit = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleParam1Edit.sizePolicy().hasHeightForWidth())
        self.titleParam1Edit.setSizePolicy(sizePolicy)
        self.titleParam1Edit.setObjectName(_fromUtf8("titleParam1Edit"))
        self.gridLayout_5.addWidget(self.titleParam1Edit, 0, 0, 1, 1)
        self.titleParam1Combo = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleParam1Combo.sizePolicy().hasHeightForWidth())
        self.titleParam1Combo.setSizePolicy(sizePolicy)
        self.titleParam1Combo.setObjectName(_fromUtf8("titleParam1Combo"))
        self.gridLayout_5.addWidget(self.titleParam1Combo, 0, 1, 1, 1)
        self.titleParam2Edit = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleParam2Edit.sizePolicy().hasHeightForWidth())
        self.titleParam2Edit.setSizePolicy(sizePolicy)
        self.titleParam2Edit.setObjectName(_fromUtf8("titleParam2Edit"))
        self.gridLayout_5.addWidget(self.titleParam2Edit, 1, 0, 1, 1)
        self.titleParam2Combo = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleParam2Combo.sizePolicy().hasHeightForWidth())
        self.titleParam2Combo.setSizePolicy(sizePolicy)
        self.titleParam2Combo.setObjectName(_fromUtf8("titleParam2Combo"))
        self.gridLayout_5.addWidget(self.titleParam2Combo, 1, 1, 1, 1)
        self.titleParam3Edit = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleParam3Edit.sizePolicy().hasHeightForWidth())
        self.titleParam3Edit.setSizePolicy(sizePolicy)
        self.titleParam3Edit.setObjectName(_fromUtf8("titleParam3Edit"))
        self.gridLayout_5.addWidget(self.titleParam3Edit, 2, 0, 1, 1)
        self.titleParam3Combo = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleParam3Combo.sizePolicy().hasHeightForWidth())
        self.titleParam3Combo.setSizePolicy(sizePolicy)
        self.titleParam3Combo.setObjectName(_fromUtf8("titleParam3Combo"))
        self.gridLayout_5.addWidget(self.titleParam3Combo, 2, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_5)

        self.retranslateUi(RiskNatToolBar)
        QtCore.QMetaObject.connectSlotsByName(RiskNatToolBar)

    def retranslateUi(self, RiskNatToolBar):
        self.groupBox.setTitle(QtGui.QApplication.translate("RiskNatToolBar", "Scale options", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("RiskNatToolBar", "Min date", None, QtGui.QApplication.UnicodeUTF8))
        self.minDateEdit.setDisplayFormat(QtGui.QApplication.translate("RiskNatToolBar", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("RiskNatToolBar", "Max date", None, QtGui.QApplication.UnicodeUTF8))
        self.maxDateEdit.setDisplayFormat(QtGui.QApplication.translate("RiskNatToolBar", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("RiskNatToolBar", "Min Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("RiskNatToolBar", "Max Y", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshScaleButton.setText(QtGui.QApplication.translate("RiskNatToolBar", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("RiskNatToolBar", "Replica", None, QtGui.QApplication.UnicodeUTF8))
        self.replicaUpCheck.setText(QtGui.QApplication.translate("RiskNatToolBar", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("RiskNatToolBar", "[mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.replicaDownCheck.setText(QtGui.QApplication.translate("RiskNatToolBar", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("RiskNatToolBar", "Chart options", None, QtGui.QApplication.UnicodeUTF8))
        self.hGridCheck.setText(QtGui.QApplication.translate("RiskNatToolBar", "H grid", None, QtGui.QApplication.UnicodeUTF8))
        self.linRegrCheck.setText(QtGui.QApplication.translate("RiskNatToolBar", "Lin regr", None, QtGui.QApplication.UnicodeUTF8))
        self.vGridCheck.setText(QtGui.QApplication.translate("RiskNatToolBar", "V grid", None, QtGui.QApplication.UnicodeUTF8))
        self.smoothCheck.setText(QtGui.QApplication.translate("RiskNatToolBar", "Smooth", None, QtGui.QApplication.UnicodeUTF8))
        self.linesCheck.setText(QtGui.QApplication.translate("RiskNatToolBar", "Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.labelsCheck.setText(QtGui.QApplication.translate("RiskNatToolBar", "Labels", None, QtGui.QApplication.UnicodeUTF8))
        self.legendCheck_2.setText(QtGui.QApplication.translate("RiskNatToolBar", "Legend", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("RiskNatToolBar", "Chart axis labels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("RiskNatToolBar", "X axis \n"
"label", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabelEdit.setText(QtGui.QApplication.translate("RiskNatToolBar", "[Date]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("RiskNatToolBar", "Y axis \n"
"label", None, QtGui.QApplication.UnicodeUTF8))
        self.yLabelEdit.setText(QtGui.QApplication.translate("RiskNatToolBar", "[mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("RiskNatToolBar", "Chart title", None, QtGui.QApplication.UnicodeUTF8))
        self.titleParam1Edit.setText(QtGui.QApplication.translate("RiskNatToolBar", "coher:", None, QtGui.QApplication.UnicodeUTF8))
        self.titleParam2Edit.setText(QtGui.QApplication.translate("RiskNatToolBar", "vel:", None, QtGui.QApplication.UnicodeUTF8))
        self.titleParam3Edit.setText(QtGui.QApplication.translate("RiskNatToolBar", "v_stdev:", None, QtGui.QApplication.UnicodeUTF8))

