# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/tool_ps_toolbar.ui'
#
# Created: Thu Oct 18 23:33:34 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ToolPSToolBar(object):
    def setupUi(self, ToolPSToolBar):
        ToolPSToolBar.setObjectName(_fromUtf8("ToolPSToolBar"))
        ToolPSToolBar.resize(905, 131)
        ToolPSToolBar.setWindowTitle(_fromUtf8(""))
        self.horizontalLayout = QtGui.QHBoxLayout(ToolPSToolBar)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(ToolPSToolBar)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.minDateEdit = QtGui.QDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minDateEdit.sizePolicy().hasHeightForWidth())
        self.minDateEdit.setSizePolicy(sizePolicy)
        self.minDateEdit.setCalendarPopup(True)
        self.minDateEdit.setObjectName(_fromUtf8("minDateEdit"))
        self.gridLayout_4.addWidget(self.minDateEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.maxDateEdit = QtGui.QDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxDateEdit.sizePolicy().hasHeightForWidth())
        self.maxDateEdit.setSizePolicy(sizePolicy)
        self.maxDateEdit.setCalendarPopup(True)
        self.maxDateEdit.setObjectName(_fromUtf8("maxDateEdit"))
        self.gridLayout_4.addWidget(self.maxDateEdit, 1, 1, 1, 1)
        self.refreshScaleButton = QtGui.QToolButton(self.groupBox)
        self.refreshScaleButton.setObjectName(_fromUtf8("refreshScaleButton"))
        self.gridLayout_4.addWidget(self.refreshScaleButton, 1, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.minYEdit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minYEdit.sizePolicy().hasHeightForWidth())
        self.minYEdit.setSizePolicy(sizePolicy)
        self.minYEdit.setObjectName(_fromUtf8("minYEdit"))
        self.horizontalLayout_2.addWidget(self.minYEdit)
        self.label_4 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setIndent(4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.maxYEdit = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxYEdit.sizePolicy().hasHeightForWidth())
        self.maxYEdit.setSizePolicy(sizePolicy)
        self.maxYEdit.setObjectName(_fromUtf8("maxYEdit"))
        self.horizontalLayout_2.addWidget(self.maxYEdit)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 2, 0, 1, 3)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(ToolPSToolBar)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.replicaUpCheck = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replicaUpCheck.sizePolicy().hasHeightForWidth())
        self.replicaUpCheck.setSizePolicy(sizePolicy)
        self.replicaUpCheck.setObjectName(_fromUtf8("replicaUpCheck"))
        self.gridLayout_5.addWidget(self.replicaUpCheck, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.replicaDistEdit = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replicaDistEdit.sizePolicy().hasHeightForWidth())
        self.replicaDistEdit.setSizePolicy(sizePolicy)
        self.replicaDistEdit.setText(_fromUtf8("28"))
        self.replicaDistEdit.setObjectName(_fromUtf8("replicaDistEdit"))
        self.horizontalLayout_3.addWidget(self.replicaDistEdit)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.replicaDownCheck = QtGui.QCheckBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replicaDownCheck.sizePolicy().hasHeightForWidth())
        self.replicaDownCheck.setSizePolicy(sizePolicy)
        self.replicaDownCheck.setObjectName(_fromUtf8("replicaDownCheck"))
        self.gridLayout_5.addWidget(self.replicaDownCheck, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(ToolPSToolBar)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setMargin(4)
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.hGridCheck = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hGridCheck.sizePolicy().hasHeightForWidth())
        self.hGridCheck.setSizePolicy(sizePolicy)
        self.hGridCheck.setObjectName(_fromUtf8("hGridCheck"))
        self.gridLayout_3.addWidget(self.hGridCheck, 0, 0, 1, 1)
        self.vGridCheck = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vGridCheck.sizePolicy().hasHeightForWidth())
        self.vGridCheck.setSizePolicy(sizePolicy)
        self.vGridCheck.setObjectName(_fromUtf8("vGridCheck"))
        self.gridLayout_3.addWidget(self.vGridCheck, 1, 0, 1, 1)
        self.linesCheck = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linesCheck.sizePolicy().hasHeightForWidth())
        self.linesCheck.setSizePolicy(sizePolicy)
        self.linesCheck.setObjectName(_fromUtf8("linesCheck"))
        self.gridLayout_3.addWidget(self.linesCheck, 2, 0, 1, 1)
        self.linRegrCheck = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linRegrCheck.sizePolicy().hasHeightForWidth())
        self.linRegrCheck.setSizePolicy(sizePolicy)
        self.linRegrCheck.setObjectName(_fromUtf8("linRegrCheck"))
        self.gridLayout_3.addWidget(self.linRegrCheck, 0, 1, 1, 1)
        self.smoothCheck = QtGui.QCheckBox(self.groupBox_3)
        self.smoothCheck.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.smoothCheck.sizePolicy().hasHeightForWidth())
        self.smoothCheck.setSizePolicy(sizePolicy)
        self.smoothCheck.setObjectName(_fromUtf8("smoothCheck"))
        self.gridLayout_3.addWidget(self.smoothCheck, 3, 0, 1, 1)
        self.labelsCheck = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelsCheck.sizePolicy().hasHeightForWidth())
        self.labelsCheck.setSizePolicy(sizePolicy)
        self.labelsCheck.setObjectName(_fromUtf8("labelsCheck"))
        self.gridLayout_3.addWidget(self.labelsCheck, 4, 0, 1, 1)
        self.polyRegrCheck = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.polyRegrCheck.sizePolicy().hasHeightForWidth())
        self.polyRegrCheck.setSizePolicy(sizePolicy)
        self.polyRegrCheck.setObjectName(_fromUtf8("polyRegrCheck"))
        self.gridLayout_3.addWidget(self.polyRegrCheck, 1, 1, 1, 1)
        self.detrendingCheck = QtGui.QCheckBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detrendingCheck.sizePolicy().hasHeightForWidth())
        self.detrendingCheck.setSizePolicy(sizePolicy)
        self.detrendingCheck.setObjectName(_fromUtf8("detrendingCheck"))
        self.gridLayout_3.addWidget(self.detrendingCheck, 2, 1, 1, 1)
        self.legendCheck = QtGui.QCheckBox(self.groupBox_3)
        self.legendCheck.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legendCheck.sizePolicy().hasHeightForWidth())
        self.legendCheck.setSizePolicy(sizePolicy)
        self.legendCheck.setObjectName(_fromUtf8("legendCheck"))
        self.gridLayout_3.addWidget(self.legendCheck, 3, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(ToolPSToolBar)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.xLabelEdit = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xLabelEdit.sizePolicy().hasHeightForWidth())
        self.xLabelEdit.setSizePolicy(sizePolicy)
        self.xLabelEdit.setObjectName(_fromUtf8("xLabelEdit"))
        self.gridLayout_2.addWidget(self.xLabelEdit, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setIndent(4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.yLabelEdit = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yLabelEdit.sizePolicy().hasHeightForWidth())
        self.yLabelEdit.setSizePolicy(sizePolicy)
        self.yLabelEdit.setObjectName(_fromUtf8("yLabelEdit"))
        self.gridLayout_2.addWidget(self.yLabelEdit, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(ToolPSToolBar)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.titleParam0Edit = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleParam0Edit.sizePolicy().hasHeightForWidth())
        self.titleParam0Edit.setSizePolicy(sizePolicy)
        self.titleParam0Edit.setObjectName(_fromUtf8("titleParam0Edit"))
        self.gridLayout.addWidget(self.titleParam0Edit, 0, 0, 1, 1)
        self.titleParam0Combo = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleParam0Combo.sizePolicy().hasHeightForWidth())
        self.titleParam0Combo.setSizePolicy(sizePolicy)
        self.titleParam0Combo.setObjectName(_fromUtf8("titleParam0Combo"))
        self.gridLayout.addWidget(self.titleParam0Combo, 0, 1, 1, 1)
        self.titleParam1Edit = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleParam1Edit.sizePolicy().hasHeightForWidth())
        self.titleParam1Edit.setSizePolicy(sizePolicy)
        self.titleParam1Edit.setObjectName(_fromUtf8("titleParam1Edit"))
        self.gridLayout.addWidget(self.titleParam1Edit, 1, 0, 1, 1)
        self.titleParam1Combo = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleParam1Combo.sizePolicy().hasHeightForWidth())
        self.titleParam1Combo.setSizePolicy(sizePolicy)
        self.titleParam1Combo.setObjectName(_fromUtf8("titleParam1Combo"))
        self.gridLayout.addWidget(self.titleParam1Combo, 1, 1, 1, 1)
        self.titleParam2Edit = QtGui.QLineEdit(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleParam2Edit.sizePolicy().hasHeightForWidth())
        self.titleParam2Edit.setSizePolicy(sizePolicy)
        self.titleParam2Edit.setObjectName(_fromUtf8("titleParam2Edit"))
        self.gridLayout.addWidget(self.titleParam2Edit, 2, 0, 1, 1)
        self.titleParam2Combo = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleParam2Combo.sizePolicy().hasHeightForWidth())
        self.titleParam2Combo.setSizePolicy(sizePolicy)
        self.titleParam2Combo.setObjectName(_fromUtf8("titleParam2Combo"))
        self.gridLayout.addWidget(self.titleParam2Combo, 2, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_5)

        self.retranslateUi(ToolPSToolBar)
        QtCore.QMetaObject.connectSlotsByName(ToolPSToolBar)

    def retranslateUi(self, ToolPSToolBar):
        self.groupBox.setTitle(QtGui.QApplication.translate("ToolPSToolBar", "Scale options", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ToolPSToolBar", "Min date", None, QtGui.QApplication.UnicodeUTF8))
        self.minDateEdit.setDisplayFormat(QtGui.QApplication.translate("ToolPSToolBar", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ToolPSToolBar", "Max date", None, QtGui.QApplication.UnicodeUTF8))
        self.maxDateEdit.setDisplayFormat(QtGui.QApplication.translate("ToolPSToolBar", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshScaleButton.setToolTip(QtGui.QApplication.translate("ToolPSToolBar", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshScaleButton.setText(QtGui.QApplication.translate("ToolPSToolBar", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ToolPSToolBar", "Min Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ToolPSToolBar", "Max Y", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ToolPSToolBar", "Replica", None, QtGui.QApplication.UnicodeUTF8))
        self.replicaUpCheck.setText(QtGui.QApplication.translate("ToolPSToolBar", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ToolPSToolBar", "[mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.replicaDownCheck.setText(QtGui.QApplication.translate("ToolPSToolBar", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ToolPSToolBar", "Chart options", None, QtGui.QApplication.UnicodeUTF8))
        self.hGridCheck.setText(QtGui.QApplication.translate("ToolPSToolBar", "H grid", None, QtGui.QApplication.UnicodeUTF8))
        self.vGridCheck.setText(QtGui.QApplication.translate("ToolPSToolBar", "V grid", None, QtGui.QApplication.UnicodeUTF8))
        self.linesCheck.setText(QtGui.QApplication.translate("ToolPSToolBar", "Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.linRegrCheck.setText(QtGui.QApplication.translate("ToolPSToolBar", "Lin trend", None, QtGui.QApplication.UnicodeUTF8))
        self.smoothCheck.setText(QtGui.QApplication.translate("ToolPSToolBar", "Smooth", None, QtGui.QApplication.UnicodeUTF8))
        self.labelsCheck.setText(QtGui.QApplication.translate("ToolPSToolBar", "Labels", None, QtGui.QApplication.UnicodeUTF8))
        self.polyRegrCheck.setText(QtGui.QApplication.translate("ToolPSToolBar", "Poly trend", None, QtGui.QApplication.UnicodeUTF8))
        self.detrendingCheck.setText(QtGui.QApplication.translate("ToolPSToolBar", "Detrending", None, QtGui.QApplication.UnicodeUTF8))
        self.legendCheck.setText(QtGui.QApplication.translate("ToolPSToolBar", "Legend", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("ToolPSToolBar", "Chart axis labels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ToolPSToolBar", "X axis \n"
"label", None, QtGui.QApplication.UnicodeUTF8))
        self.xLabelEdit.setText(QtGui.QApplication.translate("ToolPSToolBar", "[Date]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ToolPSToolBar", "Y axis \n"
"label", None, QtGui.QApplication.UnicodeUTF8))
        self.yLabelEdit.setText(QtGui.QApplication.translate("ToolPSToolBar", "[mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("ToolPSToolBar", "Chart title", None, QtGui.QApplication.UnicodeUTF8))
        self.titleParam0Edit.setText(QtGui.QApplication.translate("ToolPSToolBar", "coher.:", None, QtGui.QApplication.UnicodeUTF8))
        self.titleParam1Edit.setText(QtGui.QApplication.translate("ToolPSToolBar", "vel.:", None, QtGui.QApplication.UnicodeUTF8))
        self.titleParam2Edit.setText(QtGui.QApplication.translate("ToolPSToolBar", "v_stdev.:", None, QtGui.QApplication.UnicodeUTF8))

